Created Room table for admin
thesiriusacademy/tsa-dashboard pull request #30
Opened 2024-04-15 10:06 UTC by 06hpathak

2024-04-15 10:33 UTC, amitad16 requested changes
added comments

2024-04-15 10:33 UTC, amitad16 commented on src/hooks/use12CandleRoomDeletion.js
Please use `useMutation` for this

2024-04-15 10:33 UTC, amitad16 commented on src/pages/admin/View12CandlesRoomsModal.js
> +const ViewContentModal = ({ open, onClose, item }) => {
Rename this to `View12CandlesRoomModal`

2024-04-15 10:33 UTC, amitad16 commented on src/pages/admin/Create12CandlesRoomModal.js
> +const AddRoomModal = ({ open, onClose }) => {
Assign same naming to file name and component name

2024-04-15 10:33 UTC, amitad16 commented on src/hooks/usePagination12CandlesRoom.js
> +import TWELVE_CANDLES_GAME_ID from 'utils/constants';
Are you able to import it here?

But here you are not importing it.
https://github.com/thesiriusacademy/tsa-dashboard/pull/30/files#diff-b99195b45e9f1d84f4f48a688cba270d50b7782cfd24e6c310718cdad47b7298R3

2024-04-15 12:00 UTC, amitad16 requested changes

2024-04-15 13:34 UTC, 06hpathak commented on src/pages/admin/View12CandlesRoomsModal.js
> +const ViewContentModal = ({ open, onClose, item }) => {
done

2024-04-15 14:24 UTC, 06hpathak commented on src/hooks/use12CandleRoomDeletion.js
done

2024-04-15 14:25 UTC, 06hpathak commented on src/hooks/usePagination12CandlesRoom.js
> +import TWELVE_CANDLES_GAME_ID from 'utils/constants';
done with different method

2024-04-15 14:25 UTC, 06hpathak commented on package.json
> +    "date-fns": "^3.6.0",
switched to moment

2024-04-15 14:25 UTC, 06hpathak commented on src/hooks/use12CandleRoomDeletion.js
done

2024-04-15 14:25 UTC, 06hpathak commented on package.json
> +    "date-fns": "^3.6.0",
done

2024-04-15 14:27 UTC, 06hpathak commented on src/pages/admin/Create12CandlesRoomModal.js
> +const AddRoomModal = ({ open, onClose }) => {
done

2024-04-16 04:10 UTC, amitad16 requested changes
added some comments

2024-04-16 04:10 UTC, amitad16 commented on src/hooks/useContentDeletion.js
> +const delteContent = async ({ _id }) => {
Name it `roomId` instead of `_id`

2024-04-16 04:10 UTC, amitad16 commented on src/pages/admin/RoomForm.js
> +  const { mutateAsync: mutateAsync1 } = useEdit12CandlesRooms();
Please rename the variables as below

```suggestion
  const { mutateAsync: mutateCreateRoomAsync } = useCreate12CandlesRoom();
  const { mutateAsync: mutateEditRoomAsync } = useEdit12CandlesRooms();
```

2024-04-16 04:10 UTC, amitad16 commented on src/pages/admin/RoomForm.js
> +          const editdata = await mutateAsync1(values);
```suggestion
          const editdata = await mutateEditRoomAsync(values);
```

2024-04-16 04:10 UTC, amitad16 commented on src/pages/admin/RoomForm.js
> +          const data = await mutateAsync(values);
```suggestion
          const data = await mutateCreateRoomAsync(values);
```

2024-04-16 04:11 UTC, amitad16 commented on package.json
> +    "date-fns": "^3.6.0",
Please remove this package -> delete package-lock.json ->  and reinstall dependencies

2024-04-16 04:14 UTC, amitad16 commented on src/pages/admin/View12CandlesRoomsModal.js
> +const ViewContentModal = ({ open, onClose, item }) => {
I dont see it renamed....it is still `ViewContentModal`

2024-04-16 04:32 UTC, 06hpathak commented on src/pages/admin/View12CandlesRoomsModal.js
> +const ViewContentModal = ({ open, onClose, item }) => {
done

2024-04-16 04:51 UTC, 06hpathak commented on package.json
> +    "date-fns": "^3.6.0",
done

2024-04-16 05:15 UTC, 06hpathak commented on src/hooks/use12CandleRoomDeletion.js
> +const delteRoom = async ({ _id }) => {
done

2024-04-16 05:18 UTC, 06hpathak commented on src/hooks/useContentDeletion.js
> +const delteContent = async ({ _id }) => {
updated it as contentId

2024-04-16 05:20 UTC, 06hpathak commented on src/pages/admin/RoomForm.js
> +  const { mutateAsync: mutateAsync1 } = useEdit12CandlesRooms();
done

2024-04-16 05:21 UTC, 06hpathak commented on src/pages/admin/RoomForm.js
> +          const editdata = await mutateAsync1(values);
done

2024-04-16 05:21 UTC, 06hpathak commented on src/pages/admin/RoomForm.js
> +          const data = await mutateAsync(values);
done

2024-04-16 05:37 UTC, amitad16 approved these changes
LGTM

2024-04-16 05:44 UTC, merged